server:
  port: 8081

logging:
  path: logs
  file: userManager.log

spring:
  application:
    name: UserManager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql?serverTimezone=GMT
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.course.model
  mapper-locations: /mapper/*.xml
